/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleCTA: typeof import('./resources/js/Bricks/ArticleCTA.vue')['default']
    BeforeAfterChart: typeof import('./resources/js/Bricks/BeforeAfterChart.vue')['default']
    BentoCard: typeof import('./resources/js/Component/BentoCard.vue')['default']
    BentoGrid: typeof import('./resources/js/Bricks/BentoGrid.vue')['default']
    BryanAuthor: typeof import('./resources/js/Bricks/BryanAuthor.vue')['default']
    Button: typeof import('./resources/js/Component/Button.vue')['default']
    CheckBubble: typeof import('./resources/js/Component/CheckBubble.vue')['default']
    CTA: typeof import('./resources/js/Bricks/CTA.vue')['default']
    FAQ: typeof import('./resources/js/Bricks/FAQ.vue')['default']
    Fifty: typeof import('./resources/js/Bricks/Fifty.vue')['default']
    FiftyImage: typeof import('./resources/js/Component/FiftyImage.vue')['default']
    Footer: typeof import('./resources/js/Bricks/Footer.vue')['default']
    Header: typeof import('./resources/js/Bricks/Header.vue')['default']
    Heading: typeof import('./resources/js/Component/Heading.vue')['default']
    Hero: typeof import('./resources/js/Bricks/Hero.vue')['default']
    Main: typeof import('./resources/js/Layouts/Main.vue')['default']
    PositionCarousel: typeof import('./resources/js/Bricks/PositionCarousel.vue')['default']
    Process: typeof import('./resources/js/Bricks/Process.vue')['default']
    Row: typeof import('./resources/js/Component/Row.vue')['default']
    SalaryChart: typeof import('./resources/js/Component/SalaryChart.vue')['default']
    SavingsRow: typeof import('./resources/js/Bricks/SavingsRow.vue')['default']
    StoryCards: typeof import('./resources/js/Bricks/StoryCards.vue')['default']
    TestimonialLogoCloud: typeof import('./resources/js/Bricks/TestimonialLogoCloud.vue')['default']
  }
}
