/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleCTA: typeof import('./resources/js/Blocks/ArticleCTA.vue')['default']
    BeforeAfterChart: typeof import('./resources/js/Blocks/BeforeAfterChart.vue')['default']
    BentoCard: typeof import('./resources/js/Components/BentoCard.vue')['default']
    BentoGrid: typeof import('./resources/js/Blocks/BentoGrid.vue')['default']
    BryanAuthor: typeof import('./resources/js/Blocks/BryanAuthor.vue')['default']
    Button: typeof import('./resources/js/Components/Button.vue')['default']
    CheckBubble: typeof import('./resources/js/Components/CheckBubble.vue')['default']
    CTA: typeof import('./resources/js/Blocks/CTA.vue')['default']
    FAQ: typeof import('./resources/js/Blocks/FAQ.vue')['default']
    Fifty: typeof import('./resources/js/Blocks/Fifty.vue')['default']
    FiftyImage: typeof import('./resources/js/Components/FiftyImage.vue')['default']
    Footer: typeof import('./resources/js/Blocks/Footer.vue')['default']
    Header: typeof import('./resources/js/Blocks/Header.vue')['default']
    Heading: typeof import('./resources/js/Components/Heading.vue')['default']
    Hero: typeof import('./resources/js/Blocks/Hero.vue')['default']
    Main: typeof import('./resources/js/Layouts/Main.vue')['default']
    PositionCarousel: typeof import('./resources/js/Blocks/PositionCarousel.vue')['default']
    Process: typeof import('./resources/js/Blocks/Process.vue')['default']
    Row: typeof import('./resources/js/Components/Row.vue')['default']
    SalaryChart: typeof import('./resources/js/Components/SalaryChart.vue')['default']
    SavingsRow: typeof import('./resources/js/Blocks/SavingsRow.vue')['default']
    StoryCards: typeof import('./resources/js/Blocks/StoryCards.vue')['default']
    TestimonialLogoCloud: typeof import('./resources/js/Blocks/TestimonialLogoCloud.vue')['default']
  }
}
